Feat/gh43-44-67-68 justification dialog transfer history; fixes #43 #44 #67 #68
RHEAGROUP/DEH-CommonJ pull request #19
Opened 2022-04-08 14:28 UTC by nathanatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEH-CommonJ/pulls) open
- [x] I have verified that I am following the DEH-CommonJ [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEH-CommonJ/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

- [x] Implemented the justification dialog and local exchange history

2022-06-01 14:48 UTC, antoineatrhea requested changes
minor changes

2022-06-01 14:48 UTC, antoineatrhea commented on src/main/java/HubController/HubController.java
> +     * @throws TransactionException
Missing doc

2022-06-01 14:48 UTC, antoineatrhea commented on src/main/java/HubController/HubController.java
> +     * @throws TransactionException
Missing doc

2022-06-01 14:48 UTC, antoineatrhea commented on src/main/java/ViewModels/ExchangeHistory/ExchangeHistoryRenderDataProvider.java
> +}
Missing EOF

2022-06-01 14:48 UTC, antoineatrhea commented on src/main/java/Views/ExchangeHistory/package-info.java
> +package Views.ExchangeHistory;
Missing EOF

2022-06-01 14:48 UTC, antoineatrhea commented on src/main/java/Views/Interfaces/IDialog.java
>  }
Missing EOF

2022-06-02 07:31 UTC, alexatrhea approved these changes

2022-06-03 15:10 UTC, merged