Feat/gh12 hub session header
RHEAGROUP/DEH-CommonJ pull request #2
Opened 2021-08-26 13:15 UTC by nathanatstariongroup

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEH-MDSYSML/pulls) open
- [x] I have verified that I am following the DEH-CommonJ [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEH-CommonJ/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
fixes RHEAGROUP/DEH-MDSYSML#12

- [x] Added Session Header inormation

2021-08-30 08:53 UTC, samatrhea requested changes
did some spot checks, can you have a look at all headers. they reference the sysml project, not the common project.

2021-08-30 08:53 UTC, samatrhea commented on src/main/java/App/AppContainer.java
> + * The DEH-MDSYSML is free software; you can redistribute it and/or
incorrect project name

2021-08-30 15:13 UTC, arielleatrhea commented on src/main/java/Views/HubLogin.java
> +                JOptionPane.showMessageDialog(this.loginPanelContainer, "Please select an valid server address to continue");
"a valid server address"

2021-08-30 15:13 UTC, arielleatrhea approved these changes
Seems good

2021-09-02 08:02 UTC, samatrhea approved these changes

2021-09-02 08:03 UTC, merged